export const profile = {
  firstName: "Ígor",
  lastName: "Paslauski",
  fullName: "Ígor Paslauski Pedroso de Oliveira",
  shortName: "Paslauski",
  mark: "IP",
  role: "Engenheiro de software",
  headline: "Sistemas que agem no mundo real.",
  lede: "Full stack com quase seis anos em ERP, contabilidade e integrações que não podem falhar na segunda-feira. No tempo livre, invento linguagens.",
  location: "Ijuí, RS",
  locationDetail: "Brasil · disponível para remoto",
  availability:
    "Aberto a projetos, consultoria e oportunidades full-time — especialmente onde performance, integração e clareza de produto importam.",
  education: "Ciência da Computação · UNIJUÍ",
  years: "5+",
  email: "igor.paslauski123@gmail.com",
  phoneDisplay: "+55 (55) 99731-1689",
  phoneTel: "+5555997311689",
  whatsapp: "5555997311689",
  cv: "/cv-igor-paslauski.pdf",
  photo: "/perfil.jpg",
  site: "https://paslauski.com.br",
  socials: {
    github: "https://github.com/IgorPaslauski",
    linkedin: "https://www.linkedin.com/in/igor-paslauski-de-oliveira/",
    instagram: "https://www.instagram.com/igor_paslauski/",
    medium: "https://medium.com/@igor.pedroso123",
  },
  interests: ["Compiladores", "UX de sistemas densos", "Open source", "IA aplicada", "Eventos de tecnologia"],
} as const;
